package org.catinthedark.jvcrplotter.game

object States {
    val SPLASH_SCREEN = "SPLASH_SCREEN"
    val TITLE_SCREEN = "TITLE_SCREEN"
    val CODE_EDITOR_SCREEN = "CODE_EDITOR_SCREEN"
    val TUTORIAL_STATE = "TUTORIAL_STATE"
    val START_NEW_GAME_STATE = "START_NEW_GAME_STATE"
    val PLOTTING_SCREEN = "PLOTTING_SCREEN_STATE"
    val WORKSPACE_SCREEN = "WORKSPACE_SCREEN_STATE"
    val TASK_SCREEN = "TASK_SCREEN_STATE"
    val MAN_PAGE_SCREEN = "MAN_PAGE_SCREEN_STATE"
    val SUCCESS_SCREEN = "SUCCESS_SCREEN_STATE"
}
